In [3]:
import pandas as pd

inputfile = "nba_2013.csv"

df = pd.read_csv(inputfile)

In [4]:
df.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'PER', 'TS%', '3PAr',
       'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%',
       'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP'],
      dtype='object')

In [5]:
df.head()

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,1,Quincy Acy,PF,22,TOR,29,342,15.9,0.632,0.027,...,15.6,14.7,0.7,0.4,1.1,0.157,-0.6,1.0,0.5,0.2
1,2,Jeff Adrien,PF,26,CHA,52,713,13.4,0.493,0.012,...,13.1,15.6,0.5,0.4,1.0,0.064,-2.9,-0.4,-3.3,-0.2
2,3,Arron Afflalo,SF,27,ORL,64,2307,13.0,0.527,0.265,...,12.1,22.5,1.5,0.5,2.0,0.042,-0.4,-1.9,-2.3,-0.2
3,4,Josh Akognon,PG,26,DAL,3,9,15.3,0.625,0.500,...,0.0,20.3,0.0,0.0,0.0,0.196,4.3,-4.9,-0.6,0.0
4,5,Cole Aldrich,C,24,TOT,45,388,11.1,0.563,0.000,...,20.6,12.7,0.1,0.4,0.6,0.070,-4.4,0.4,-3.9,-0.2

In [6]:
df.describe()

,Rk,Age,G,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
count,573.000000,573.000000,573.000000,573.000000,572.000000,569.000000,569.000000,569.000000,572.000000,572.000000,...,570.000000,572.000000,573.000000,573.000000,573.000000,572.000000,573.000000,573.000000,573.000000,573.000000
mean,234.607330,26.535777,49.219895,1112.923211,12.127972,0.499309,0.236636,0.278002,5.690734,14.268182,...,14.621404,18.703322,1.186562,1.109424,2.295812,0.060797,-1.778360,-0.492845,-2.268761,0.522688
std,135.580961,4.230781,25.925670,878.099964,6.040580,0.099934,0.213113,0.244251,5.548980,7.055579,...,8.253539,5.199738,1.968674,1.155958,2.826353,0.102521,3.573037,1.994670,4.339752,1.182688
min,1.000000,19.000000,1.000000,0.000000,-30.200000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-2.500000,-0.200000,-1.500000,-0.779000,-29.500000,-10.600000,-31.100000,-1.500000
25%,115.000000,23.000000,27.000000,325.000000,9.300000,0.472000,0.009000,0.165000,1.900000,9.100000,...,10.700000,15.100000,0.000000,0.200000,0.100000,0.028000,-3.200000,-1.600000,-3.600000,-0.100000
50%,240.000000,26.000000,53.000000,936.000000,12.400000,0.516000,0.222000,0.236000,3.900000,13.300000,...,13.300000,18.400000,0.400000,0.700000,1.300000,0.075000,-1.300000,-0.500000,-1.700000,0.100000
75%,350.000000,30.000000,75.000000,1837.000000,15.900000,0.553000,0.405000,0.333000,8.400000,18.800000,...,16.900000,22.125000,1.900000,1.700000,3.600000,0.116000,0.400000,0.900000,0.300000,0.800000
max,469.000000,40.000000,82.000000,3167.000000,31.600000,0.931000,0.873000,4.000000,56.700000,67.700000,...,100.000000,37.200000,14.600000,6.300000,19.300000,0.353000,9.000000,4.900000,10.800000,9.200000

In [8]:
df2 = df.copy()
df2 = df2.loc[df["Tm"] == "CHI"]
df2

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
14,11,Louis Amundson,PF,30,CHI,1,2,0.0,0.000,0.000,...,0.0,23.0,0.0,0.0,0.0,-0.274,-9.0,-8.6,-17.6,0.0
51,41,Marco Belinelli,SG,26,CHI,73,1882,10.4,0.513,0.362,...,10.7,18.7,1.3,1.6,3.0,0.076,-1.1,-1.3,-2.5,-0.2
64,54,Carlos Boozer,PF,31,CHI,79,2546,17.1,0.510,0.002,...,12.3,25.8,1.4,4.3,5.7,0.108,-1.4,0.7,-0.7,0.8
82,68,Jimmy Butler,SF,23,CHI,82,2134,15.2,0.574,0.205,...,9.2,14.6,4.4,2.6,7.0,0.158,0.7,1.0,1.7,2.0
108,88,Daequan Cook,SG,25,CHI,33,276,4.0,0.366,0.565,...,7.4,20.1,-0.6,0.3,-0.3,-0.048,-5.9,-2.5,-8.4,-0.4
132,106,Luol Deng,SF,27,CHI,75,2903,15.1,0.508,0.213,...,10.6,21.5,3.0,3.3,6.3,0.105,0.5,0.6,1.1,2.3
185,149,Taj Gibson,PF,27,CHI,65,1459,14.4,0.518,0.009,...,13.2,18.1,1.0,2.3,3.3,0.109,-2.5,1.9,-0.6,0.5
204,166,Richard Hamilton,SG,34,CHI,50,1088,10.6,0.481,0.109,...,14.2,25.0,-0.6,0.9,0.4,0.016,-2.9,-2.1,-5.1,-0.8
234,192,Kirk Hinrich,PG,32,CHI,60,1764,10.8,0.493,0.431,...,17.5,14.7,1.0,2.1,3.1,0.085,-1.1,-0.1,-1.2,0.4
365,301,Nazr Mohammed,C,35,CHI,63,693,10.8,0.414,0.011,...,10.7,14.9,0.0,1.2,1.2,0.082,-4.3,1.6,-2.7,-0.1
386,318,Joakim Noah,C,27,CHI,66,2426,18.1,0.534,0.008,...,19.3,17.2,2.7,4.7,7.3,0.145,0.2,4.7,4.9,4.2
429,350,Vladimir Radmanovic,PF,32,CHI,25,144,6.3,0.372,0.628,...,13.6,16.4,-0.2,0.3,0.1,0.020,-3.0,1.3,-1.6,0.0
441,360,Nate Robinson,PG,28,CHI,82,2086,17.4,0.540,0.378,...,12.6,25.1,3.5,2.4,5.9,0.136,3.1,-1.6,1.6,1.9
493,404,Marquis Teague,PG,19,CHI,48,392,6.0,0.412,0.204,...,22.6,18.2,-0.7,0.4,-0.3,-0.031,-5.8,-0.9,-6.7,-0.5
506,413,Malcolm Thomas,PF,24,CHI,7,36,16.7,0.558,0.000,...,15.7,16.3,0.1,0.1,0.1,0.166,-0.6,1.9,1.4,0.0

In [9]:
dummies = pd.get_dummies(df2['Pos'])
dummies

     C  PF  PG  SF  SG
14   0   1   0   0   0
51   0   0   0   0   1
64   0   1   0   0   0
82   0   0   0   1   0
108  0   0   0   0   1
132  0   0   0   1   0
185  0   1   0   0   0
204  0   0   0   0   1
234  0   0   1   0   0
365  1   0   0   0   0
386  1   0   0   0   0
429  0   1   0   0   0
441  0   0   1   0   0
493  0   0   1   0   0
506  0   1   0   0   0

In [14]:
df3 = pd.concat([df2,dummies], axis = 1 , sort = True)
df3.drop('Pos', axis = 1, inplace = True)
df3

,Rk,Player,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,WS/48,OBPM,DBPM,BPM,VORP,C,PF,PG,SF,SG
14,11,Louis Amundson,30,CHI,1,2,0.0,0.000,0.000,0.000,...,-0.274,-9.0,-8.6,-17.6,0.0,0,1,0,0,0
51,41,Marco Belinelli,26,CHI,73,1882,10.4,0.513,0.362,0.275,...,0.076,-1.1,-1.3,-2.5,-0.2,0,0,0,0,1
64,54,Carlos Boozer,31,CHI,79,2546,17.1,0.510,0.002,0.232,...,0.108,-1.4,0.7,-0.7,0.8,0,1,0,0,0
82,68,Jimmy Butler,23,CHI,82,2134,15.2,0.574,0.205,0.455,...,0.158,0.7,1.0,1.7,2.0,0,0,0,1,0
108,88,Daequan Cook,25,CHI,33,276,4.0,0.366,0.565,0.083,...,-0.048,-5.9,-2.5,-8.4,-0.4,0,0,0,0,1
132,106,Luol Deng,27,CHI,75,2903,15.1,0.508,0.213,0.258,...,0.105,0.5,0.6,1.1,2.3,0,0,0,1,0
185,149,Taj Gibson,27,CHI,65,1459,14.4,0.518,0.009,0.297,...,0.109,-2.5,1.9,-0.6,0.5,0,1,0,0,0
204,166,Richard Hamilton,34,CHI,50,1088,10.6,0.481,0.109,0.162,...,0.016,-2.9,-2.1,-5.1,-0.8,0,0,0,0,1
234,192,Kirk Hinrich,32,CHI,60,1764,10.8,0.493,0.431,0.232,...,0.085,-1.1,-0.1,-1.2,0.4,0,0,1,0,0
365,301,Nazr Mohammed,35,CHI,63,693,10.8,0.414,0.011,0.261,...,0.082,-4.3,1.6,-2.7,-0.1,1,0,0,0,0
386,318,Joakim Noah,27,CHI,66,2426,18.1,0.534,0.008,0.376,...,0.145,0.2,4.7,4.9,4.2,1,0,0,0,0
429,350,Vladimir Radmanovic,32,CHI,25,144,6.3,0.372,0.628,0.070,...,0.020,-3.0,1.3,-1.6,0.0,0,1,0,0,0
441,360,Nate Robinson,28,CHI,82,2086,17.4,0.540,0.378,0.183,...,0.136,3.1,-1.6,1.6,1.9,0,0,1,0,0
493,404,Marquis Teague,19,CHI,48,392,6.0,0.412,0.204,0.142,...,-0.031,-5.8,-0.9,-6.7,-0.5,0,0,1,0,0
506,413,Malcolm Thomas,24,CHI,7,36,16.7,0.558,0.000,0.444,...,0.166,-0.6,1.9,1.4,0.0,0,1,0,0,0

In [16]:
import numpy as np

df4 = df3.copy()
df4['log(MP)'] = np.log(df4['MP'])
df4

,Rk,Player,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,OBPM,DBPM,BPM,VORP,C,PF,PG,SF,SG,log(MP)
14,11,Louis Amundson,30,CHI,1,2,0.0,0.000,0.000,0.000,...,-9.0,-8.6,-17.6,0.0,0,1,0,0,0,0.693147
51,41,Marco Belinelli,26,CHI,73,1882,10.4,0.513,0.362,0.275,...,-1.1,-1.3,-2.5,-0.2,0,0,0,0,1,7.540090
64,54,Carlos Boozer,31,CHI,79,2546,17.1,0.510,0.002,0.232,...,-1.4,0.7,-0.7,0.8,0,1,0,0,0,7.842279
82,68,Jimmy Butler,23,CHI,82,2134,15.2,0.574,0.205,0.455,...,0.7,1.0,1.7,2.0,0,0,0,1,0,7.665753
108,88,Daequan Cook,25,CHI,33,276,4.0,0.366,0.565,0.083,...,-5.9,-2.5,-8.4,-0.4,0,0,0,0,1,5.620401
132,106,Luol Deng,27,CHI,75,2903,15.1,0.508,0.213,0.258,...,0.5,0.6,1.1,2.3,0,0,0,1,0,7.973500
185,149,Taj Gibson,27,CHI,65,1459,14.4,0.518,0.009,0.297,...,-2.5,1.9,-0.6,0.5,0,1,0,0,0,7.285507
204,166,Richard Hamilton,34,CHI,50,1088,10.6,0.481,0.109,0.162,...,-2.9,-2.1,-5.1,-0.8,0,0,0,0,1,6.992096
234,192,Kirk Hinrich,32,CHI,60,1764,10.8,0.493,0.431,0.232,...,-1.1,-0.1,-1.2,0.4,0,0,1,0,0,7.475339
365,301,Nazr Mohammed,35,CHI,63,693,10.8,0.414,0.011,0.261,...,-4.3,1.6,-2.7,-0.1,1,0,0,0,0,6.541030
386,318,Joakim Noah,27,CHI,66,2426,18.1,0.534,0.008,0.376,...,0.2,4.7,4.9,4.2,1,0,0,0,0,7.793999
429,350,Vladimir Radmanovic,32,CHI,25,144,6.3,0.372,0.628,0.070,...,-3.0,1.3,-1.6,0.0,0,1,0,0,0,4.969813
441,360,Nate Robinson,28,CHI,82,2086,17.4,0.540,0.378,0.183,...,3.1,-1.6,1.6,1.9,0,0,1,0,0,7.643004
493,404,Marquis Teague,19,CHI,48,392,6.0,0.412,0.204,0.142,...,-5.8,-0.9,-6.7,-0.5,0,0,1,0,0,5.971262
506,413,Malcolm Thomas,24,CHI,7,36,16.7,0.558,0.000,0.444,...,-0.6,1.9,1.4,0.0,0,1,0,0,0,3.583519

In [19]:
def rescale_zero2one(x, lo, hi):
    return(x-lo) / (hi - lo)

s = pd.Series([-1,0.1,1.,3.])
s = s.apply(rescale_zero2one, args=(s.min(),s.max()))
s

0    0.000
1    0.275
2    0.500
3    1.000
dtype: float64

In [20]:
lo = df4['VORP'].min()
hi = df4['VORP'].max()

df4['scaled(VORP)'] = df4['VORP'].apply(rescale_zero2one, args = (lo,hi))
df4

,Rk,Player,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,DBPM,BPM,VORP,C,PF,PG,SF,SG,log(MP),scaled(VORP)
14,11,Louis Amundson,30,CHI,1,2,0.0,0.000,0.000,0.000,...,-8.6,-17.6,0.0,0,1,0,0,0,0.693147,0.16
51,41,Marco Belinelli,26,CHI,73,1882,10.4,0.513,0.362,0.275,...,-1.3,-2.5,-0.2,0,0,0,0,1,7.540090,0.12
64,54,Carlos Boozer,31,CHI,79,2546,17.1,0.510,0.002,0.232,...,0.7,-0.7,0.8,0,1,0,0,0,7.842279,0.32
82,68,Jimmy Butler,23,CHI,82,2134,15.2,0.574,0.205,0.455,...,1.0,1.7,2.0,0,0,0,1,0,7.665753,0.56
108,88,Daequan Cook,25,CHI,33,276,4.0,0.366,0.565,0.083,...,-2.5,-8.4,-0.4,0,0,0,0,1,5.620401,0.08
132,106,Luol Deng,27,CHI,75,2903,15.1,0.508,0.213,0.258,...,0.6,1.1,2.3,0,0,0,1,0,7.973500,0.62
185,149,Taj Gibson,27,CHI,65,1459,14.4,0.518,0.009,0.297,...,1.9,-0.6,0.5,0,1,0,0,0,7.285507,0.26
204,166,Richard Hamilton,34,CHI,50,1088,10.6,0.481,0.109,0.162,...,-2.1,-5.1,-0.8,0,0,0,0,1,6.992096,0.00
234,192,Kirk Hinrich,32,CHI,60,1764,10.8,0.493,0.431,0.232,...,-0.1,-1.2,0.4,0,0,1,0,0,7.475339,0.24
365,301,Nazr Mohammed,35,CHI,63,693,10.8,0.414,0.011,0.261,...,1.6,-2.7,-0.1,1,0,0,0,0,6.541030,0.14
386,318,Joakim Noah,27,CHI,66,2426,18.1,0.534,0.008,0.376,...,4.7,4.9,4.2,1,0,0,0,0,7.793999,1.00
429,350,Vladimir Radmanovic,32,CHI,25,144,6.3,0.372,0.628,0.070,...,1.3,-1.6,0.0,0,1,0,0,0,4.969813,0.16
441,360,Nate Robinson,28,CHI,82,2086,17.4,0.540,0.378,0.183,...,-1.6,1.6,1.9,0,0,1,0,0,7.643004,0.54
493,404,Marquis Teague,19,CHI,48,392,6.0,0.412,0.204,0.142,...,-0.9,-6.7,-0.5,0,0,1,0,0,5.971262,0.06
506,413,Malcolm Thomas,24,CHI,7,36,16.7,0.558,0.000,0.444,...,1.9,1.4,0.0,0,1,0,0,0,3.583519,0.16